FROM openjdk:17-slim

ENV GIT_BRANCH {{ git_branch }}
ENV GIT_COMMIT {{ git_commit }}
ENV BUILD_TIMESTAMP {{ build_timestamp }}

WORKDIR /opt/wordle-solver-api

ADD wordle-solver-api-*.tgz .

EXPOSE 8000

CMD [ "/opt/wordle-solver-api/bin/wordle-solver-api" ]
