FROM openjdk:17-slim

LABEL org.opencontainers.image.source https://github.com/ruchira088/wordle-solver-api

ENV GIT_BRANCH {{ git_branch }}
ENV GIT_COMMIT {{ git_commit }}
ENV BUILD_TIMESTAMP {{ build_timestamp }}

WORKDIR /opt/wordle-solver-api

ADD wordle-solver-api-*.tgz .

EXPOSE 8000

CMD [ "/opt/wordle-solver-api/bin/wordle-solver-api" ]